require:
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/**/*
    - vendor/**/*
Style/HashSyntax:
  EnforcedShorthandSyntax: never
Style/Documentation:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  EnforcedStyle: brackets
Bundler/OrderedGems:
  Enabled: true
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/ClassAndModuleChildren:
  Enabled: false
# Metrics/BlockLength:
#   Exclude:
#     - config/environments/development.rb
Rails/I18nLocaleTexts:
  Enabled: false
