name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby 3.2.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Setup deploy key
        run: |
          aws s3 cp s3://${{ secrets.SSH_KEY_S3_BUCKET }}/${{ secrets.SSH_KEY_S3_OBJECT_KEY }} ${{ secrets.CAP_DEPLOY_KEY_PATH }}
          chmod 0600 ${{ secrets.CAP_DEPLOY_KEY_PATH }}
      - name: Deploy using capistrano
        run: bin/cap ${{ secrets.TARGET_ENVIRONMENT }} deploy
        env:
          CAP_DEPLOY_SERVER: ${{ secrets.CAP_DEPLOY_SERVER }}
          CAP_DEPLOY_USER: ${{ secrets.CAP_DEPLOY_USER }}
          CAP_DEPLOY_KEY_PATH: ${{ secrets.CAP_DEPLOY_KEY_PATH }}
          CAP_HOME: ${{ secrets.CAP_HOME }}
